"""initial baseline

Revision ID: 956eb32c2e91
Revises: 
Create Date: 2026-03-09 13:46:09.008980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956eb32c2e91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # If tables already exist (pre-Alembic database), skip creation — just stamp.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if "users" in set(inspector.get_table_names()):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_email_type'), ['email_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_recipient'), ['recipient'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('coverage_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', sa.Text(), nullable=True),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('last_calculated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coverage_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coverage_scores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coverage_scores_user_id'), ['user_id'], unique=False)

    op.create_table('dismissed_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rec_key', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dismissed_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dismissed_recommendations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dismissed_recommendations_user_id'), ['user_id'], unique=False)

    op.create_table('emergency_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_code', sa.String(length=20), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('holder_name', sa.String(length=200), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('include_coverage_amounts', sa.Boolean(), nullable=False),
    sa.Column('include_deductibles', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_cards_access_code'), ['access_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_emergency_cards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_cards_user_id'), ['user_id'], unique=False)

    op.create_table('exposures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exposure_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exposures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exposures_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposures_user_id'), ['user_id'], unique=False)

    op.create_table('inbound_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_addresses_alias'), ['alias'], unique=True)
        batch_op.create_index(batch_op.f('ix_inbound_addresses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_addresses_user_id'), ['user_id'], unique=True)

    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('profile_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_contacts_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address_street', sa.String(length=300), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=50), nullable=True),
    sa.Column('address_zip', sa.String(length=20), nullable=True),
    sa.Column('is_homeowner', sa.Boolean(), nullable=False),
    sa.Column('is_renter', sa.Boolean(), nullable=False),
    sa.Column('has_dependents', sa.Boolean(), nullable=False),
    sa.Column('has_vehicle', sa.Boolean(), nullable=False),
    sa.Column('owns_business', sa.Boolean(), nullable=False),
    sa.Column('high_net_worth', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)

    op.create_table('inbound_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inbound_address_id', sa.Integer(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inbound_address_id'], ['inbound_addresses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_emails_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_emails_inbound_address_id'), ['inbound_address_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_emails_user_id'), ['user_id'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exposure_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('replaces_policy_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('carrier', sa.String(length=120), nullable=False),
    sa.Column('policy_number', sa.String(length=80), nullable=False),
    sa.Column('nickname', sa.String(length=200), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('coverage_amount', sa.Integer(), nullable=True),
    sa.Column('deductible', sa.Integer(), nullable=True),
    sa.Column('premium_amount', sa.Integer(), nullable=True),
    sa.Column('plan_subtype', sa.String(length=30), nullable=True),
    sa.Column('out_of_pocket_max', sa.Integer(), nullable=True),
    sa.Column('family_deductible', sa.Integer(), nullable=True),
    sa.Column('family_oop_max', sa.Integer(), nullable=True),
    sa.Column('deductible_type', sa.String(length=20), nullable=True),
    sa.Column('deductible_period_start', sa.Date(), nullable=True),
    sa.Column('deductible_applied', sa.Integer(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exposure_id'], ['exposures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['replaces_policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_exposure_id'), ['exposure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_policy_number'), ['policy_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_policy_type'), ['policy_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_replaces_policy_id'), ['replaces_policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_user_id'), ['user_id'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('counterparty_name', sa.String(length=200), nullable=False),
    sa.Column('counterparty_type', sa.String(length=50), nullable=False),
    sa.Column('counterparty_email', sa.String(length=255), nullable=True),
    sa.Column('carrier', sa.String(length=200), nullable=True),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('coverage_types', sa.String(length=500), nullable=True),
    sa.Column('coverage_amount', sa.Integer(), nullable=True),
    sa.Column('additional_insured', sa.Boolean(), nullable=False),
    sa.Column('waiver_of_subrogation', sa.Boolean(), nullable=False),
    sa.Column('minimum_coverage', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_user_id'), ['user_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_filed', sa.Date(), nullable=False),
    sa.Column('date_resolved', sa.Date(), nullable=True),
    sa.Column('amount_claimed', sa.Integer(), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_policy_id'), ['policy_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_policy_id'), ['policy_id'], unique=False)

    op.create_table('coverage_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('limit', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coverage_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coverage_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coverage_items_policy_id'), ['policy_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('doc_type', sa.String(length=50), server_default='policy', nullable=False),
    sa.Column('extraction_status', sa.String(length=20), server_default='none', nullable=False),
    sa.Column('cached_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_object_key'), ['object_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_documents_policy_id'), ['policy_id'], unique=False)

    op.create_table('lease_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('counterparty_name', sa.String(length=200), nullable=True),
    sa.Column('counterparty_email', sa.String(length=255), nullable=True),
    sa.Column('property_address', sa.String(length=500), nullable=True),
    sa.Column('lease_clause_text', sa.Text(), nullable=True),
    sa.Column('requirements_json', sa.Text(), nullable=False),
    sa.Column('access_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_requirements_access_code'), ['access_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_lease_requirements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_requirements_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_requirements_user_id'), ['user_id'], unique=False)

    op.create_table('policy_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_details_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_details_policy_id'), ['policy_id'], unique=False)

    op.create_table('policy_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inbound_email_id', sa.Integer(), nullable=True),
    sa.Column('matched_policy_id', sa.Integer(), nullable=True),
    sa.Column('carrier', sa.String(length=200), nullable=True),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('policy_type', sa.String(length=50), nullable=True),
    sa.Column('extraction_data', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('object_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inbound_email_id'], ['inbound_emails.id'], ),
    sa.ForeignKeyConstraint(['matched_policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_drafts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_drafts_user_id'), ['user_id'], unique=False)

    op.create_table('policy_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_email', sa.String(length=255), nullable=False),
    sa.Column('permission', sa.String(length=10), nullable=False),
    sa.Column('role_label', sa.String(length=30), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_shares_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_shares_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_shares_policy_id'), ['policy_id'], unique=False)

    op.create_table('premium_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('premium_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_premium_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_premium_history_policy_id'), ['policy_id'], unique=False)

    op.create_table('premiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('premiums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_premiums_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_premiums_policy_id'), ['policy_id'], unique=False)

    op.create_table('renewal_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('remind_at', sa.Date(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('renewal_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_renewal_reminders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_renewal_reminders_policy_id'), ['policy_id'], unique=False)

    op.create_table('certificate_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('remind_at', sa.Date(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_reminders_certificate_id'), ['certificate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_reminders_id'), ['id'], unique=False)

    op.create_table('compliance_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lease_requirement_id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.Column('checked_against', sa.String(length=20), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('unclear_count', sa.Integer(), nullable=False),
    sa.Column('tenant_name', sa.String(length=200), nullable=True),
    sa.Column('tenant_email', sa.String(length=255), nullable=True),
    sa.Column('coi_file_key', sa.String(length=500), nullable=True),
    sa.Column('coi_file_data', sa.LargeBinary(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lease_requirement_id'], ['lease_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_checks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_checks_lease_requirement_id'), ['lease_requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_checks_user_id'), ['user_id'], unique=False)

    op.create_table('policy_deltas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=500), nullable=True),
    sa.Column('new_value', sa.String(length=500), nullable=True),
    sa.Column('delta_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_deltas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_deltas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_deltas_policy_id'), ['policy_id'], unique=False)

    op.create_table('delta_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delta_id', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('possible_reasons', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['delta_id'], ['policy_deltas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delta_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delta_explanations_delta_id'), ['delta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delta_explanations_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delta_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delta_explanations_id'))
        batch_op.drop_index(batch_op.f('ix_delta_explanations_delta_id'))

    op.drop_table('delta_explanations')
    with op.batch_alter_table('policy_deltas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_deltas_policy_id'))
        batch_op.drop_index(batch_op.f('ix_policy_deltas_id'))

    op.drop_table('policy_deltas')
    with op.batch_alter_table('compliance_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_checks_user_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_checks_lease_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_checks_id'))

    op.drop_table('compliance_checks')
    with op.batch_alter_table('certificate_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_reminders_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_reminders_certificate_id'))

    op.drop_table('certificate_reminders')
    with op.batch_alter_table('renewal_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_renewal_reminders_policy_id'))
        batch_op.drop_index(batch_op.f('ix_renewal_reminders_id'))

    op.drop_table('renewal_reminders')
    with op.batch_alter_table('premiums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_premiums_policy_id'))
        batch_op.drop_index(batch_op.f('ix_premiums_id'))

    op.drop_table('premiums')
    with op.batch_alter_table('premium_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_premium_history_policy_id'))
        batch_op.drop_index(batch_op.f('ix_premium_history_id'))

    op.drop_table('premium_history')
    with op.batch_alter_table('policy_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_shares_policy_id'))
        batch_op.drop_index(batch_op.f('ix_policy_shares_owner_id'))
        batch_op.drop_index(batch_op.f('ix_policy_shares_id'))

    op.drop_table('policy_shares')
    with op.batch_alter_table('policy_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_drafts_user_id'))
        batch_op.drop_index(batch_op.f('ix_policy_drafts_id'))

    op.drop_table('policy_drafts')
    with op.batch_alter_table('policy_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_details_policy_id'))
        batch_op.drop_index(batch_op.f('ix_policy_details_id'))

    op.drop_table('policy_details')
    with op.batch_alter_table('lease_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_requirements_user_id'))
        batch_op.drop_index(batch_op.f('ix_lease_requirements_policy_id'))
        batch_op.drop_index(batch_op.f('ix_lease_requirements_id'))
        batch_op.drop_index(batch_op.f('ix_lease_requirements_access_code'))

    op.drop_table('lease_requirements')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_policy_id'))
        batch_op.drop_index(batch_op.f('ix_documents_object_key'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))

    op.drop_table('documents')
    with op.batch_alter_table('coverage_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coverage_items_policy_id'))
        batch_op.drop_index(batch_op.f('ix_coverage_items_id'))

    op.drop_table('coverage_items')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_policy_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_policy_id'))
        batch_op.drop_index(batch_op.f('ix_claims_id'))

    op.drop_table('claims')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_user_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_policy_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_id'))

    op.drop_table('certificates')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_user_id'))
        batch_op.drop_index(batch_op.f('ix_policies_scope'))
        batch_op.drop_index(batch_op.f('ix_policies_replaces_policy_id'))
        batch_op.drop_index(batch_op.f('ix_policies_policy_type'))
        batch_op.drop_index(batch_op.f('ix_policies_policy_number'))
        batch_op.drop_index(batch_op.f('ix_policies_id'))
        batch_op.drop_index(batch_op.f('ix_policies_exposure_id'))

    op.drop_table('policies')
    with op.batch_alter_table('inbound_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_emails_user_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_emails_inbound_address_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_emails_id'))

    op.drop_table('inbound_emails')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profiles_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('profile_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_contacts_user_id'))
        batch_op.drop_index(batch_op.f('ix_profile_contacts_id'))

    op.drop_table('profile_contacts')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_token'))
        batch_op.drop_index(batch_op.f('ix_password_resets_id'))

    op.drop_table('password_resets')
    with op.batch_alter_table('inbound_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_addresses_user_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_addresses_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_addresses_alias'))

    op.drop_table('inbound_addresses')
    with op.batch_alter_table('exposures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exposures_user_id'))
        batch_op.drop_index(batch_op.f('ix_exposures_id'))

    op.drop_table('exposures')
    with op.batch_alter_table('emergency_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_cards_user_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_cards_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_cards_access_code'))

    op.drop_table('emergency_cards')
    with op.batch_alter_table('dismissed_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dismissed_recommendations_user_id'))
        batch_op.drop_index(batch_op.f('ix_dismissed_recommendations_id'))

    op.drop_table('dismissed_recommendations')
    with op.batch_alter_table('coverage_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coverage_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_coverage_scores_id'))

    op.drop_table('coverage_scores')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_id'))

    op.drop_table('announcements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_recipient'))
        batch_op.drop_index(batch_op.f('ix_email_logs_id'))
        batch_op.drop_index(batch_op.f('ix_email_logs_email_type'))

    op.drop_table('email_logs')
    # ### end Alembic commands ###
